# Generated by Django 2.2.5 on 2019-11-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id_cupon', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=25)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=3)),
                ('costo_puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id_hamburguesa', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('puntos_ham', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=15)),
                ('fecha_nac', models.DateField()),
                ('foto_perfil', models.ImageField(upload_to='')),
                ('puntos_usu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('costo_total', models.IntegerField()),
                ('puntos_total', models.IntegerField()),
                ('id_cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Cupones')),
                ('id_hamburguesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Hamburguesa')),
                ('rut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Hist_Cupones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_puntos_his', models.IntegerField()),
                ('id_cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Cupones')),
                ('rut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
    ]
